<?php

namespace Database\Seeders;

use App\Models\Crop;
use Illuminate\Database\Seeder;

class CropSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $crops = [
            [
                'name' => 'Avocado',
                'description' => 'Avocado plants', 
                'lowest_temperature' => '16', 
                'highest_temperature' => '25', 
                'lowest_humidity' => '60', 
                'highest_humidity' => '80', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '2500', 
                'average_market_price' => '22.22',
                'amount_in_kg' => '90',
                'in_demand' => '0',
            ],
            [
                'name' => 'Maize',
                'description' => 'Maize plants', 
                'lowest_temperature' => '18', 
                'highest_temperature' => '23', 
                'lowest_humidity' => '13', 
                'highest_humidity' => '14', 
                'lowest_atmospheric_pressure' => '40000', 
                'highest_atmospheric_pressure' => '6000', 
                'average_market_price' => '22.96',
                'amount_in_kg' => '90',
                'in_demand' => '1',
            ],
            [
                'name' => 'Cabbage',
                'description' => 'Cabbage plants', 
                'lowest_temperature' => '16', 
                'highest_temperature' => '21', 
                'lowest_humidity' => '800', 
                'highest_humidity' => '2200', 
                'lowest_atmospheric_pressure' => '95', 
                'highest_atmospheric_pressure' => '98',
                'average_market_price' => '16.60',
                'amount_in_kg' => '126',    
                'in_demand' => '0', 
            ],
            [
                'name' => 'Mango',
                'description' => 'Mango plants', 
                'lowest_temperature' => '27', 
                'highest_temperature' => '36', 
                'lowest_humidity' => '50', 
                'highest_humidity' => '100', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '600', 
                'average_market_price' => '20.10',
                'amount_in_kg' => '126',
                'in_demand' => '0',
            ],
            [
                'name' => 'Cashew Nuts',
                'description' => 'Cashwe Nuts plants', 
                'lowest_temperature' => '24', 
                'highest_temperature' => '28', 
                'lowest_humidity' => '67', 
                'highest_humidity' => '70', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '700', 
                'average_market_price' => '45',
                'amount_in_kg' => '20',
                'in_demand' => '0',
            ],
            [
                'name' => 'Cassava',
                'description' => 'Cassava plants', 
                'lowest_temperature' => '25', 
                'highest_temperature' => '29', 
                'lowest_humidity' => '60', 
                'highest_humidity' => '70', 
                'lowest_atmospheric_pressure' => '250', 
                'highest_atmospheric_pressure' => '1500', 
                'average_market_price' => '27.02',
                'amount_in_kg' => '99',
                'in_demand' => '0',
            ],
            [
                'name' => 'Coffee',
                'description' => 'Coffee plants', 
                'lowest_temperature' => '18', 
                'highest_temperature' => '21', 
                'lowest_humidity' => '50', 
                'highest_humidity' => '100', 
                'lowest_atmospheric_pressure' => '1000', 
                'highest_atmospheric_pressure' => '6000', 
                'average_market_price' => '700',
                'amount_in_kg' => '1',
                'in_demand' => '0',
            ],
            [
                'name' => 'Rice',
                'description' => 'Rice plants', 
                'lowest_temperature' => '15', 
                'highest_temperature' => '27', 
                'lowest_humidity' => '60', 
                'highest_humidity' => '80', 
                'lowest_atmospheric_pressure' => '60', 
                'highest_atmospheric_pressure' => '3050', 
                'average_market_price' => '170',
                'amount_in_kg' => '1',
                'in_demand' => '1',
            ],
            [
                'name' => 'Potato',
                'description' => 'Potato plants', 
                'lowest_temperature' => '15', 
                'highest_temperature' => '20', 
                'lowest_humidity' => '50', 
                'highest_humidity' => '85', 
                'lowest_atmospheric_pressure' => '1600', 
                'highest_atmospheric_pressure' => '3200', 
                'average_market_price' => '64',
                'amount_in_kg' => '50',
                'in_demand' => '1',
            ],
            [
                'name' => 'Sweet Potato',
                'description' => 'Sweet Potato plants', 
                'lowest_temperature' => '24', 
                'highest_temperature' => '35', 
                'lowest_humidity' => '85', 
                'highest_humidity' => '90', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '2500', 
                'average_market_price' => '29.59',
                'amount_in_kg' => '98',
                'in_demand' => '1',
            ],
            [
                'name' => 'Tea',
                'description' => 'Tea Leaves', 
                'lowest_temperature' => '13', 
                'highest_temperature' => '21', 
                'lowest_humidity' => '70', 
                'highest_humidity' => '90', 
                'lowest_atmospheric_pressure' => '700', 
                'highest_atmospheric_pressure' => '3000', 
                'average_market_price' => '140',
                'amount_in_kg' => '1',
                'in_demand' => '0',
            ],
            [
                'name' => 'Wheat',
                'description' => 'Wheat plants', 
                'lowest_temperature' => '21', 
                'highest_temperature' => '24', 
                'lowest_humidity' => '50', 
                'highest_humidity' => '60', 
                'lowest_atmospheric_pressure' => '1200', 
                'highest_atmospheric_pressure' => '1800', 
                'average_market_price' => '33.33',
                'amount_in_kg' => '90',
                'in_demand' => '1',
            ],
            [
                'name' => 'Tomato',
                'description' => 'Tomato plants', 
                'lowest_temperature' => '19', 
                'highest_temperature' => '27', 
                'lowest_humidity' => '80', 
                'highest_humidity' => '90', 
                'lowest_atmospheric_pressure' => '1500', 
                'highest_atmospheric_pressure' => '3000',
                'average_market_price' => '70.11',
                'amount_in_kg' => '64',
                'in_demand' => '1', 
            ],
            [
                'name' => 'Orange',
                'description' => 'Orange fruits', 
                'lowest_temperature' => '21', 
                'highest_temperature' => '32', 
                'lowest_humidity' => '50', 
                'highest_humidity' => '70', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '2100', 
                'average_market_price' => '36.76',
                'amount_in_kg' => '93',
                'in_demand' => '0',
            ],
            [
                'name' => 'Onion',
                'description' => 'Onion plants', 
                'lowest_temperature' => '13', 
                'highest_temperature' => '35', 
                'lowest_humidity' => '65', 
                'highest_humidity' => '70', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '1900', 
                'average_market_price' => '64.81',
                'amount_in_kg' => '13',
                'in_demand' => '1',
            ],
            [
                'name' => 'Banana',
                'description' => 'Banana plants', 
                'lowest_temperature' => '26', 
                'highest_temperature' => '30', 
                'lowest_humidity' => '65', 
                'highest_humidity' => '90', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '1800', 
                'average_market_price' => '45.5',
                'amount_in_kg' => '14',
                'in_demand' => '0',
            ],
            [
                'name' => 'Peas',
                'description' => 'Peas plants', 
                'lowest_temperature' => '16', 
                'highest_temperature' => '21', 
                'lowest_humidity' => '70', 
                'highest_humidity' => '100', 
                'lowest_atmospheric_pressure' => '750', 
                'highest_atmospheric_pressure' => '5000', 
                'average_market_price' => '46.50',
                'amount_in_kg' => '51',
                'in_demand' => '0',
            ],
            [
                'name' => 'Lemon',
                'description' => 'Lemon plants', 
                'lowest_temperature' => '21', 
                'highest_temperature' => '38', 
                'lowest_humidity' => '50', 
                'highest_humidity' => '100', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '2000', 
                'average_market_price' => '29.55',
                'amount_in_kg' => '95',
                'in_demand' => '0',
            ],
            [
                'name' => 'Kale',
                'description' => 'Kale plants', 
                'lowest_temperature' => '13', 
                'highest_temperature' => '24', 
                'lowest_humidity' => '95', 
                'highest_humidity' => '95', 
                'lowest_atmospheric_pressure' => '800', 
                'highest_atmospheric_pressure' => '2200', 
                'average_market_price' => '67.20',
                'amount_in_kg' => '50',
                'in_demand' => '1',
            ],
            [
                'name' => 'Millet',
                'description' => 'Millet plants', 
                'lowest_temperature' => '26', 
                'highest_temperature' => '29', 
                'lowest_humidity' => '11', 
                'highest_humidity' => '25', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '2400', 
                'average_market_price' => '73.75',
                'amount_in_kg' => '90',
                'in_demand' => '1',
            ],
            [
                'name' => 'Sorghum',
                'description' => 'Sorghum plants', 
                'lowest_temperature' => '26', 
                'highest_temperature' => '34', 
                'lowest_humidity' => '12', 
                'highest_humidity' => '13', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '2500', 
                'average_market_price' => '38.98',
                'amount_in_kg' => '90',
                'in_demand' => '1',
            ],
            [
                'name' => 'Beans',
                'description' => 'Beans plants', 
                'lowest_temperature' => '18', 
                'highest_temperature' => '29', 
                'lowest_humidity' => '75', 
                'highest_humidity' => '85', 
                'lowest_atmospheric_pressure' => '1000', 
                'highest_atmospheric_pressure' => '2100',
                'average_market_price' => '66.25',
                'amount_in_kg' => '90',
                'in_demand' => '1', 
            ],
            [
                'name' => 'Carrot',
                'description' => 'Carrot plants', 
                'lowest_temperature' => '15', 
                'highest_temperature' => '18', 
                'lowest_humidity' => '95', 
                'highest_humidity' => '100', 
                'lowest_atmospheric_pressure' => '500', 
                'highest_atmospheric_pressure' => '2000', 
                'average_market_price' => '268.94',
                'amount_in_kg' => '13',
                'in_demand' => '0',
            ],
            [
                'name' => 'Pineapple',
                'description' => 'Pineapple plants', 
                'lowest_temperature' => '20', 
                'highest_temperature' => '30', 
                'lowest_humidity' => '70', 
                'highest_humidity' => '80', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '2000', 
                'average_market_price' => '59.31',
                'amount_in_kg' => '13',
                'in_demand' => '0',
            ],
            [
                'name' => 'Pawpaw',
                'description' => 'Pawpaw plants', 
                'lowest_temperature' => '21', 
                'highest_temperature' => '23', 
                'lowest_humidity' => '30', 
                'highest_humidity' => '40', 
                'lowest_atmospheric_pressure' => '0', 
                'highest_atmospheric_pressure' => '2100', 
                'average_market_price' => '44.84',
                'amount_in_kg' => '54',
                'in_demand' => '0',
            ], 


         
        ];

        foreach ($crops as $crop) {
            $crop = Crop::create([
                   'name' => $crop['name'],
                   'description' => $crop['description'],
                   'lowest_temperature' => $crop['lowest_temperature'],
                   'highest_temperature' => $crop['highest_temperature'],
                   'lowest_humidity' => $crop['lowest_humidity'],
                   'highest_humidity' => $crop['highest_humidity'],
                   'lowest_atmospheric_pressure' => $crop['lowest_atmospheric_pressure'],
                   'highest_atmospheric_pressure' => $crop['highest_atmospheric_pressure'],
                   'average_market_price' => $crop['average_market_price'],
                   'amount_in_kg' => $crop['amount_in_kg'],
                   'in_demand' => $crop['in_demand'],
                 ]);
        }
    }
}
